server:
  port: 8081


eureka: 
 instance:
  hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud: 
   gateway: 
    routes: 
     - id: Question-SERVICE
       uri: lb://Question-SERVICE 
       predicates: 
        - Path=/api/question/**